### ISSUE TITLE
Fall damage is messed up

### ISSUE THREAD

**Issue by Xodetaetl** [TreyRuffy/TreysDoubleJump#7]
I've activated fall damage but survival players still don't take any. The only way I can take damage is by flying high in creative mode then switch to survival and fall to death.

Config:
```
DisableFallDamage: false
Velocity:
  Forward: 0.0
  Up: 0.5
```
